version: "3.9"

services:
  java_app:
    container_name: java_app
    image: hackacode:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/fantasykingdom?useTimezone=true&serverTimezone=UTC
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=
      - DATABASE_DRIVER=com.mysql.cj.jdbc.Driver
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql:8.0.29
    ports:
    - "3307:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE
      - MYSQL_DB=fantasykingdom