version: "3.9"

services:
  java_app:
    container_name: java_app
    image: hackacode:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/fantasykingdom
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE
      - MYSQL_DB=fantasykingdom
  frontend:
    container_name: frontend
    build: ../hackacode-frontend
    ports:
      - "80:80"


    ports:
      - "80:80"


